### ISSUE TITLE
Version compatibility issue with sqlite3 in Linux CentOS-7 even after installing the Sqlite-3.9.2

### ISSUE THREAD

**Issue by mohammedamirk** [jobic10/e-voting-with-django#11]
(evoting-venv3.8) [root@ip-172-31-84-84 e-voting-with-django]# python3.8 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 70, in <module>
    check_sqlite_version()
  File "/root/e-voting-main/evoting-venv3.8/lib64/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 67, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
(evoting-venv3.8) [root@ip-172-31-84-84 e-voting-with-django]# ls -l | grep sqlite
-rw-r--r-- 1 root root    0 Jul 25 19:03 db.sqlite3

**Comment by jobic10** [comment]
Hi there, 
What steps led to this, please?

**Comment by mohammedamirk** [comment]
Hey. This issue is resolved now by downgrading the django version to 2.1.2

**Comment by mohammedamirk** [comment]
Hey. This issue is resolved now by downgrading the django version to 2.1.2.
