### ISSUE TITLE
OSError: cannot load library 'gobject-2.0-0'

### ISSUE THREAD

**Issue by Yash7302mm** [jobic10/e-voting-with-django#13]
Traceback (most recent call last):
  File "C:\Users\yashm\Downloads\e-voting-with-django-main\e-voting-with-django-main\manage.py", line 24, in <module>
    main()
  File "C:\Users\yashm\Downloads\e-voting-with-django-main\e-voting-with-django-main\manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\management\base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\management\base.py", line 443, in execute
    self.check()
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\management\base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\yashm\Downloads\e-voting-with-django-main\e-voting-with-django-main\e_voting\urls.py", line 25, in <module>
    path('administrator/', include('administrator.urls')),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\yashm\Downloads\e-voting-with-django-main\e-voting-with-django-main\administrator\urls.py", line 2, in <module>
    from . import views
  File "C:\Users\yashm\Downloads\e-voting-with-django-main\e-voting-with-django-main\administrator\views.py", line 10, in <module>
    from django_renderpdf.views import PDFView
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django_renderpdf\views.py", line 10, in <module>
    from django_renderpdf import helpers
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\django_renderpdf\helpers.py", line 13, in <module>
    from weasyprint import default_url_fetcher
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\weasyprint\__init__.py", line 341, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\weasyprint\css\__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\weasyprint\css\computed_values.py", line 11, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\weasyprint\text\ffi.py", line 428, in <module>
    gobject = _dlopen(
              ^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\weasyprint\text\ffi.py", line 417, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yashm\AppData\Local\Programs\Python\Python311\Lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by ramcharan0** [comment]
same issue here

**Comment by jobic10** [comment]
Hi devs,
Can you check out this closed issue [here](https://github.com/jobic10/e-voting-with-django/issues/10#issuecomment-1099550953)

**Comment by Yash7302mm** [comment]
Thank you so much it worked.

**Comment by MilindMack** [comment]
> Thank you so much it worked.

Request to guide the same steps

**Comment by Yash7302mm** [comment]
Try installing gtk it'll work
