### ISSUE TITLE
 makemigrations

### ISSUE THREAD

**Issue by CareyOsafo** [jobic10/e-voting-with-django#15]
I contacted you earlier this week about an issue I was facing with your system. Below is a screenshot of the issue
![Uploading Screenshot 2023-07-25 at 10.35.58 AM (2).png…]()

**Comment by jobic10** [comment]
Kindly provide steps to reproduce, attach screenshots also.
The attached link appears to be broken.

**Comment by CareyOsafo** [comment]
when trying to makemigrations it also gave this error:

Traceback (most recent call last):
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/core/management/base.py", line 453, in execute
    self.check()
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/core/checks/templates.py", line 55, in check_for_template_tags_with_the_same_name
    for conf in settings.TEMPLATES:
                ^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eddieosafo/e-voting-with-django/manage.py", line 23, in <module>
    main()
  File "/Users/eddieosafo/e-voting-with-django/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/core/management/base.py", line 425, in run_from_argv
    connections.close_all()
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/utils/connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/utils/connection.py", line 76, in all
    return [
           ^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
                ^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/db/utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eddieosafo/e-voting-with-django/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings'

**Comment by jobic10** [comment]
Kindly confirm the Django version you have installed.

Ensure all packages are installed and give it a try.
Let's know if you are having further issues.

**Comment by CareyOsafo** [comment]
I am still having this issue

**Comment by CareyOsafo** [comment]
Would it be possible for me to arrange an online meeting so you could help me resolve this issue

**Comment by CareyOsafo** [comment]
<img width="1440" alt="Screenshot 2023-08-01 at 11 56 28 AM" src="https://github.com/jobic10/e-voting-with-django/assets/81256554/5adad3b0-78d5-4083-9dfe-a490fd6539fc">

**Comment by CareyOsafo** [comment]
<img width="1440" alt="Screenshot 2023-08-01 at 12 04 20 PM" src="https://github.com/jobic10/e-voting-with-django/assets/81256554/b615335d-ba5c-43a9-a638-f72a921b5c13">

**Comment by CareyOsafo** [comment]
I have done that and uploaded it onto the git repository

**Comment by jobic10** [comment]
> <img alt="Screenshot 2023-08-01 at 12 04 20 PM" width="1440" src="https://user-images.githubusercontent.com/81256554/257508414-b615335d-ba5c-43a9-a638-f72a921b5c13.png">


`pip install django_renderpdf` 
Kindly go through the closed issues on this repo.
I am sure you'll find solution.
Apologies for the stress 💘

**Comment by CareyOsafo** [comment]
Is there a way to run this without running the makemigrations command?

**Comment by jobic10** [comment]
You'll need to migrate and runserver.
Are you still having some challenges? Share it here, so others might find a fix when they experience similar thing.
